import { generateTests } from './agents/generator';
import { validateTests } from './agents/validator';
import { humanApproval } from './human/approval';
import { generateAutomation } from './agents/automation';
import { analyzeFailure } from './agents/analysis';
import { chromium } from '@playwright/test';
import { captureDOM } from './agents/domCapture';
import config from './playwright.config';

import fs from 'fs';
import { execSync } from 'child_process';
import path from 'path';

async function run() {

  
//Need to work on this logic ===========================================
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();

await page.goto(`${config.use?.baseURL || ''}/labs`);

const domContext = await captureDOM(page);

await browser.close();
//===================================================================




// 📄 Read prompt file
const promptPath = path.resolve('prompts/manualTest.prompt.txt');
let promptTemplate = fs.readFileSync(promptPath, 'utf-8');

const manual = await generateTests(promptTemplate);
const validated = await validateTests(manual);

const approved = await humanApproval(validated);
if (!approved) return console.log("Rejected by Naman");



function validateRelevantConstants(automation: any) {
  const pages = automation.pages.map((p: any) => p.fileName);

  for (const constant of automation.constants || []) {
    const relatedPage = constant.fileName.replace('.constants.ts', 'Page.ts');

    if (!pages.includes(relatedPage)) {
      throw new Error(`❌ Unused constants generated: ${constant.fileName}`);
    }
  }
}

function validateConstantsExist(automation: any) {
  if (!automation.constants || automation.constants.length === 0) {
    throw new Error("❌ Constants not generated by AI");
  }
}

function validateBasePage(automation: any) {
  const pages = automation.pages || [];

  const hasBasePage = pages.some((p: any) =>
    p.fileName.toLowerCase().includes('basepage')
  );

  if (!hasBasePage) {
    throw new Error('❌ BasePage.ts missing in AI output');
  }

  const invalidPages = pages.filter((p: any) =>
    !p.fileName.toLowerCase().includes('basepage') &&
    !p.code.includes('extends BasePage')
  );

  if (invalidPages.length > 0) {
    throw new Error(
      `❌ Pages not extending BasePage: ${invalidPages
        .map((p: any) => p.fileName)
        .join(', ')}`
    );
  }
}
async function generateWithValidation(input: string, max = 3) {
  for (let i = 0; i < max; i++) {
    const automation = await generateAutomation(input);

    try {
      validateBasePage(automation);
      validateConstantsExist(automation);
      validateRelevantConstants(automation);

      return automation;
    } catch (e) {
      console.log(`⚠️ Attempt ${i + 1} failed:`, (e as Error).message);
    }
  }

  throw new Error("❌ Failed to generate valid framework");
}

const enrichedInput = `
TEST CASE:
${validated}

DOM CONTEXT:
${JSON.stringify(domContext, null, 2)}
`;

const automation = await generateWithValidation(enrichedInput);

console.log("Automation Output:", automation);

function toStringSafe(data: any) {
  if (typeof data === 'string') return data;
  if (data?.code) return data.code;
  return JSON.stringify(data, null, 2);
}

// ✅ Write pages
if (automation.pages && Array.isArray(automation.pages)) {
  for (const page of automation.pages) {
    const filePath = `./playwright/pages/${page.fileName}`;
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, toStringSafe(page.code));
  }
}

// ✅ Write test
let testFileName = "generated.spec.ts";

if (automation.test) {
  testFileName = automation.test.fileName || testFileName;
  const testPath = `./playwright/tests/${testFileName}`;
  fs.mkdirSync(path.dirname(testPath), { recursive: true });
  fs.writeFileSync(testPath, toStringSafe(automation.test.code));
}

// ✅ Write constants
if (automation.constants && Array.isArray(automation.constants)) {
  for (const constant of automation.constants) {
    const filePath = `./playwright/constants/${constant.fileName}`;
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, toStringSafe(constant.code));
  }
}

console.log("✅ Automation generated.");

// ==============================
// 🧪 RUN PLAYWRIGHT TESTS
// ==============================

let logs = "";

try {
  execSync(`npx playwright test --reporter=json > report.json`, {
    stdio: "inherit",
  });
  console.log("✅ Tests passed");
} catch (error) {
  console.log("❌ Tests failed");

  // Read logs
  if (fs.existsSync("report.json")) {
    logs = fs.readFileSync("report.json", "utf-8");
  }

  // ==============================
  // 🧠 AI ANALYSIS
  // ==============================
  const analysis = await analyzeFailure(logs);

  console.log("\n🧠 AI ANALYSIS:\n", analysis);

  // ==============================
  // 📊 SAVE FOR ALLURE
  // ==============================
  const allureDir = "./allure-results";
  fs.mkdirSync(allureDir, { recursive: true });

  fs.writeFileSync(
    `${allureDir}/ai-analysis.txt`,
    analysis
  );

  console.log("📊 AI analysis saved to Allure");
}

}

run();